name: flutter_platform_checker
description: Shows you which platforms can be targeted by your Flutter app based on dependencies
version: 1.0.3
homepage: https://github.com/redsolver/flutter_platform_checker

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pub_api_client: ^2.0.5
  yaml: ^3.1.0
  barbecue: ^0.4.0
  tint: ^2.0.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10

executables:
  flutter_platform_checker: flutter_platform_checker
